// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ZxhZbP9C680O7SLv1bwzJK1QL7eerDg',
    appId: '1:545180119129:web:643947da2fdc9e1d214148',
    messagingSenderId: '545180119129',
    projectId: 'project-2-f2d08',
    authDomain: 'project-2-f2d08.firebaseapp.com',
    storageBucket: 'project-2-f2d08.appspot.com',
    measurementId: 'G-RH2CM2WDKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31VrIka76567OvNpkvImJcIfBoVXA3es',
    appId: '1:545180119129:android:8ddcc31e78f15e27214148',
    messagingSenderId: '545180119129',
    projectId: 'project-2-f2d08',
    storageBucket: 'project-2-f2d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1FOglw9Ev3l51JHTcKWGaCO18zEIP6Nk',
    appId: '1:545180119129:ios:3538ffe20e1b074e214148',
    messagingSenderId: '545180119129',
    projectId: 'project-2-f2d08',
    storageBucket: 'project-2-f2d08.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1FOglw9Ev3l51JHTcKWGaCO18zEIP6Nk',
    appId: '1:545180119129:ios:bce7f3836e872ae7214148',
    messagingSenderId: '545180119129',
    projectId: 'project-2-f2d08',
    storageBucket: 'project-2-f2d08.appspot.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
